development:
  adapter: postgresql
  encoding: unicode
  database: nypl_tweetwall_development
  username: postgres
  min_messages: WARNING
test:
  adapter: postgresql
  encoding: unicode
  database: nypl_tweetwall_test
  username: postgres
  min_messages: WARNING
